name: Generate Template List

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  generate-dir-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate template list
        run: |
          dirs=$(find . -maxdepth 1 -type d ! -name 'Basistemplate' ! -name '.git' ! -name '.github' ! -name '.' | sed 's|./||')
          echo "{\"templates\": [$(echo $dirs | tr ' ' ', ' | sed 's/\([^, ]\+\)/\"\1\"/g')]}" > templates.json


      - name: Commit and push the JSON file
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add templates.json
          git commit -m 'Add updated template list'
          git push
