name: Generate Directory List

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  generate-dir-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate directory list
        run: |
          dirs=$(find . -maxdepth 1 -type d ! -name 'Basistemplete' ! -name '.git' ! -name '.github' ! -name '.' | sed 's|./||')
          echo "{\"lables\": [\"$(echo $dirs | tr ' ' '\", \"')\"]}" > labels.json

      - name: Commit and push the JSON file
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add labels.json
          git commit -m 'Add updated directory list'
          git push
